#!/bin/bash

# Uncomment following line if you would like to add api key in this file
# PUUSH_API_KEY="apikeyhere"
# It is recommended that you instead set PUUSH_API_KEY as an environment variable in some startup script, like so:
# PUUSH_API_KEY="xxxxxxxxxxxxxxxxxxx"; export PUUSH_API_KEY

if [ -z "$PUUSH_API_KEY" ]
then
  echo "Set the variable PUUSH_API_KEY in $0 or with 'export PUUSH_API_KEY=\"apiKeyHere\""
  exit 1
elif [ -z "$1" ]
then
  echo "Specify a file to be uploaded"
  exit 2
elif ! [ -f "$1" -a -r "$1" ]
then
  echo "File '$1' is not valid (it is not a file or it is not readable)"
  exit 3
fi

# If we are supposed to show a link (--showlink), then pop up a dialog with it.
if [[ $* == *--showlink* ]]
then
  curl "https://puush.me/api/up" -# -F "k=$PUUSH_API_KEY" -F "z=poop" -F "f=@$1" | sed -E 's/^.+,(.+),.+,.+$/\1\n/' >> /tmp/puushlink
  zenity --info --text="`cat /tmp/puushlink`"
  rm /tmp/puushlink
# Else, upload like normal
else
  curl "https://puush.me/api/up" -# -F "k=$PUUSH_API_KEY" -F "z=poop" -F "f=@$1" | sed -E 's/^.+,(.+),.+,.+$/\1\n/'
fi
