#!/bin/bash

if [ -z "$PUUSH_API_KEY" ]
  then
    echo "Set the variable PUUSH_API_KEY with 'export PUUSH_API_KEY=\"apiKeyHere\""
    exit
fi
OIFS=$IFS
IFS=','
temp=0

curl "https://puush.me/api/up" -F "k=$PUUSH_API_KEY" -F "z=poop" -F "f=@$1" -o puushtmp

IN=$(cat puushtmp)

for x in $IN
do
    if [[ $temp = 1 ]]
      then
        echo $x
    fi
    (( temp += 1 ))
done


IFS=$OIFS
